name: enter_training_me
description: The last fitness project, I swear

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.4
  cupertino_icons: ^1.0.5
  flutter_bloc: ^8.1.2
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  build_runner: ^2.3.3
  flutter_localizations: 
    sdk: flutter   
  #get: ^4.6.5
  get:
    git:
      url: https://github.com/Jpec57/getx.git
      ref: master
  cached_network_image: ^3.2.3
  wakelock: ^0.6.2
  equatable: ^2.0.5
  dio: ^5.1.2
  flutter_secure_storage: ^8.0.0
  carousel_slider: ^4.2.1
  audioplayers: ^4.0.1
  vibration: ^1.7.7
  flutter_tts: ^3.6.3
  fl_chart: ^0.62.0
  video_player: ^2.6.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  chewie: ^1.4.0
  intl: ^0.18.1
  #feature_discovery: ^0.5.0
  auto_animated: ^3.1.0
  visibility_detector: ^0.3.3
  # visibility_detector: ^0.4.0+2
  file_picker: ^4.2.7
  # file_picker: ^5.3.0
  flutter_cache_manager: ^3.3.0
  image_picker: ^0.8.7+4
  multi_select_flutter: ^4.1.3
  flag: ^6.0.0
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  intl_utils: ^2.8.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  #copy_with_extension_gen: ^2.0.3
  flutter_lints: ^2.0.1
  hive_generator: ^2.0.0
  #freezed: ^0.15.1+1


flutter:
  generate: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/exercises/
    - assets/workouts/
    - assets/sounds/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
