name: App Deployment

on: workflow_dispatch


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build_flutter
        id: flutter_env
      # Build apk.
      - run: flutter build apk
    
      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk