name: App Deployment

on: workflow_dispatch


jobs:
  set_up: 
    uses: Jpec57/enter_training_me/.github/workflows/build_flutter.yml@v1
  deploy:
    runs-on: ubuntu-latest
    needs: set_up
    steps: 
    # Build apk.
    - run: flutter build apk
    
    # Upload generated apk to the artifacts.
    - uses: actions/upload-artifact@v1
      with:
        name: release-apk
        path: build/app/outputs/apk/release/app-release.apk