name: Flutter CI

on:
  push:
    branches:
    - master # Default: will run for every branch.    

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Flutter Env 
        uses: ./.github/actions/build_flutter
        
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
        continue-on-error: true
    
    # - run: flutter test
    