name: Flutter CI

on:
  push:
    branches:
    - master # Default will running for every branch.    

jobs:
  linter:
    uses: Jpec57/enter_training_me/.github/workflows/build_flutter.yml@v1

    steps:
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # - run: flutter test
    