name: Flutter CI

on:
  push:
    branches:
    - master # Default will running for every branch.    

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/build_flutter
        id: flutter_env
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
    
    # - run: flutter test
    