name: Flutter CI

on:
  push:
    branches:
    - master # Default will running for every branch.    

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Jpec57/enter_training_me/.github/workflows/build_flutter.yml@v1
      # Statically analyze the Dart code for any errors.
      - run: flutter analyze .
    
    # - run: flutter test
    