name: Flutter CI

on:
  push:
    branches:
    - master # Default will running for every branch.    

jobs:
  set_up: 
    uses: Jpec57/enter_training_me/.github/workflows/build_flutter.yml@v1

  linter:
    runs-on: ubuntu-latest
    needs: set_up
    steps:
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # - run: flutter test
    