name: Flutter CI

on:
  push:
    branches:
    - master # Default will running for every branch.    

jobs:
  call-workflow:
    uses: jpec57/enter_training_me/.github/workflows/build_flutter.yml@v1
  linter:
    runs-on: ubuntu-latest
    needs: build
    steps:
    # Check for any formatting issues in the code.
    - run: flutter format --set-exit-if-changed .
    
    # Statically analyze the Dart code for any errors.
    - run: flutter analyze .
    
    # - run: flutter test
    